# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: glue.aws.m.upbound.io/v1beta1
kind: Workflow
metadata:
  name: example
spec:
  forProvider:
    region: us-east-1
